import type { Language } from './i18n';

// ---------------------------------------------------------------------------
// English word pools
// ---------------------------------------------------------------------------

const EN_SHORT = [
  'run',
  'fly',
  'go',
  'win',
  'hit',
  'aim',
  'cut',
  'get',
  'set',
  'use',
  'act',
  'add',
  'ask',
  'bit',
  'box',
  'buy',
  'can',
  'cap',
  'car',
  'cat',
  'cup',
  'day',
  'dig',
  'dot',
  'dry',
  'eat',
  'end',
  'eye',
  'far',
  'fix',
  'fog',
  'fun',
  'gas',
  'hat',
  'hot',
  'ice',
  'ink',
  'jar',
  'jet',
  'job',
  'key',
  'kid',
  'lab',
  'law',
  'let',
  'lid',
  'lip',
  'log',
  'low',
  'map',
];

const EN_MEDIUM = [
  'space',
  'orbit',
  'laser',
  'storm',
  'force',
  'speed',
  'power',
  'black',
  'pulse',
  'drift',
  'craft',
  'warp',
  'nova',
  'jump',
  'burst',
  'dodge',
  'quick',
  'sharp',
  'focus',
  'track',
  'light',
  'drive',
  'surge',
  'probe',
  'vapor',
  'flame',
  'guard',
  'phase',
  'pixel',
  'solid',
  'rapid',
  'sonic',
  'prime',
  'ultra',
  'delta',
  'alpha',
  'shift',
  'blaze',
  'shock',
  'sweep',
  'flare',
  'glide',
  'pivot',
  'clash',
  'swarm',
  'plunge',
  'eject',
  'relay',
];

const EN_LONG = [
  'velocity',
  'supernova',
  'gravity',
  'asteroid',
  'dimension',
  'traverse',
  'nebula',
  'hyperspace',
  'singularity',
  'trajectory',
  'ignition',
  'catalyst',
  'resonance',
  'frequency',
  'magnitude',
  'sequence',
  'proximity',
  'momentum',
  'isolation',
  'subsystem',
  'generator',
  'threshold',
  'protocol',
  'override',
  'satellite',
  'radiation',
  'fragment',
  'collapse',
  'propulsion',
  'quantum',
  'synthetic',
  'transmit',
  'terminal',
  'electron',
  'particle',
  'wormhole',
  'vortex',
  'antimatter',
  'interstellar',
  'acceleration',
  'decelerate',
];

// ---------------------------------------------------------------------------
// Portuguese word pools
// ---------------------------------------------------------------------------

const PT_SHORT = [
  'cor',
  'luz',
  'mar',
  'sol',
  'vez',
  'voz',
  'fim',
  'bem',
  'mal',
  'paz',
  'rei',
  'lei',
  'ser',
  'ter',
  'ver',
  'dar',
  'por',
  'gem',
  'lar',
  'nau',
  'voo',
  'tom',
  'dom',
  'som',
  'fio',
  'rio',
  'mao',
  'dia',
  'era',
  'fel',
  'ar',
  'ir',
  'rir',
  'ceu',
  'pes',
  'bom',
  'sao',
  'dor',
  'mor',
  'uso',
];

const PT_MEDIUM = [
  'forca',
  'rapido',
  'pulso',
  'chama',
  'brilho',
  'vento',
  'sombra',
  'pedra',
  'campo',
  'tempo',
  'mundo',
  'ponto',
  'forma',
  'nivel',
  'mente',
  'poder',
  'turbo',
  'salto',
  'fraco',
  'carga',
  'omega',
  'prova',
  'ruido',
  'fluxo',
  'plano',
  'bloco',
  'troar',
  'surto',
  'lance',
  'golpe',
  'ritmo',
  'ardor',
  'fardo',
  'custo',
  'rumo',
  'marca',
  'nexo',
  'traco',
  'vulto',
  'claro',
];

const PT_LONG = [
  'velocidade',
  'supernova',
  'gravidade',
  'asteroide',
  'dimensao',
  'travessia',
  'nebulosa',
  'hiperespaco',
  'singularidade',
  'trajetoria',
  'ignicao',
  'catalisador',
  'ressonancia',
  'frequencia',
  'magnitude',
  'sequencia',
  'proximidade',
  'momento',
  'isolamento',
  'subsistema',
  'gerador',
  'limiar',
  'protocolo',
  'sobrecarga',
  'satelite',
  'radiacao',
  'fragmento',
  'colapso',
  'propulsao',
  'quantico',
  'sintetico',
  'transmitir',
  'terminal',
  'eletron',
  'particula',
  'buraco',
  'vortice',
  'antimateria',
  'interestelar',
  'aceleracao',
  'desacelerar',
];

const POOLS: Record<Language, { short: string[]; medium: string[]; long: string[] }> = {
  en: { short: EN_SHORT, medium: EN_MEDIUM, long: EN_LONG },
  pt: { short: PT_SHORT, medium: PT_MEDIUM, long: PT_LONG },
};

// Pick word based on current difficulty level (0–1)
export function getNextWord(difficulty: number, lang: Language = 'en'): string {
  const roll = Math.random();
  const { short, medium, long } = POOLS[lang];

  // As difficulty grows, more long/medium words appear
  const longThreshold = 0.1 + difficulty * 0.3; // 10%→40%
  const medThreshold = 0.4 + difficulty * 0.2; // 40%→60%

  let pool: string[];
  if (roll < longThreshold) {
    pool = long;
  } else if (roll < medThreshold) {
    pool = medium;
  } else {
    pool = short;
  }

  return pool[Math.floor(Math.random() * pool.length)];
}

// Distance reward scales with word length
export function getWordDistanceBoost(word: string): number {
  const len = word.length;
  if (len <= 3) return 1.0;
  if (len <= 5) return 1.5;
  if (len <= 7) return 2.2;
  return 3.5;
}
